export const DEFAULT_CONTENT = {
  settings: {
    groom: 'Ahmad',
    bride: 'Zara',
    date: '2026-06-12T16:00',
    location: 'Istanbul, Turkey',
    tagline: 'Joined by faith, united by love',
  },
  story: [
    { year: '2019', title: 'How We Met', description: 'At a community iftar during Ramadan, introduced by mutual friends. A conversation about Islamic history turned into hours of shared laughter and discovery. Neither of us knew that Allah had already written our names together.' },
    { year: '2020', title: 'Istikhara', description: "After a year of friendship and deepening respect, we both prayed Salat al-Istikhara separately. The peace that followed was undeniable. When we shared our du'as with our families, every door opened with ease." },
    { year: '2021', title: 'Family Meeting', description: 'Our families gathered for the first time over a traditional Ottoman dinner. The warmth, the shared values, and the immediate connection between both households made it clear — this was more than a union of two hearts, but of two families.' },
    { year: '2022', title: 'The Proposal (Khitbah)', description: "Ahmad, with his father and the Imam, formally asked for Zara's hand in marriage. It was a moment of profound respect, tradition, and joy. The mahr was agreed upon with love and mutual understanding." },
    { year: '2023', title: 'Engagement', description: 'A beautiful engagement ceremony at the Blue Mosque gardens, surrounded by family and friends. We exchanged rings and made our intention clear before Allah and our loved ones.' },
    { year: '2025', title: 'The Nikah', description: 'The day we become husband and wife in the sight of Allah. A sacred covenant, a new beginning, and the fulfillment of a prayer we both made years ago.' },
  ],
  ceremony: {
    quote: {
      arabic: 'وَمِنْ ءَايَـٰتِهِۦٓ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَٰجًۭا لِّتَسْكُنُوٓا۟ إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةًۭ وَرَحْمَةً ۚ إِنَّ فِى ذَٰلِكَ لَـَٔايَـٰتٍۢ لِّقَوْمٍۢ يَتَفَكَّرُونَ ٢١',
      english: 'And one of His signs is that He created for you spouses from among yourselves so that you may find comfort in them. And He has placed between you compassion and mercy. Surely in this are signs for people who reflect.',
      reference: 'Surah Ar-Rum, 30:21',
    },
    nikah: {
      venue: 'Süleymaniye Mosque',
      address: 'Süleymaniye Mah., Fatih, Istanbul',
      date: 'Friday, 12 June 2026 · 4:00 PM',
      info: 'Brothers and sisters are warmly welcome. Please arrive 20 minutes early.',
    },
    walima: {
      venue: 'Bosphorus Pavilion',
      address: 'Üsküdar, Istanbul',
      date: 'Saturday, 13 June 2026 · 1:00 PM',
      info: 'A reception feast to celebrate follows the ceremony. All guests invited.',
    },
  },
  party: [
    { name: 'Yusuf', role: 'Best Man' },
    { name: 'Omar', role: 'Groomsman' },
    { name: 'Aisha', role: 'Maid of Honor' },
    { name: 'Fatima', role: 'Bridesmaid' },
    { name: 'Layla', role: 'Bridesmaid' },
    { name: 'Ibrahim', role: 'Usher' },
  ],
  guidelines: [
    { title: 'Separate Seating', description: 'A prayer-conscious gathering with separate seating for brothers and sisters.' },
    { title: 'Halal Only', description: 'All food and refreshments served will be 100% halal.' },
    { title: 'Nasheed Only', description: 'Entertainment will be modest — no podcasts, only nasheeds and reminders.' },
    { title: 'Photography', description: 'Photos are welcome! Please keep them respectful and modest.' },
  ],
  gallery: [
    { url: '', caption: 'Our first meeting' },
    { url: '', caption: 'A walk by the Bosphorus' },
    { url: '', caption: 'The proposal' },
    { url: '', caption: 'Family gathering' },
    { url: '', caption: 'Engagement day' },
    { url: '', caption: 'Together in du’a' },
    { url: '', caption: 'Our favorite café' },
    { url: '', caption: 'Counting blessings' },
    { url: '', caption: 'The big news' },
  ],
  location: {
    venue: 'Süleymaniye Mosque',
    address: 'Süleymaniye Mah., Fatih',
    city: 'Istanbul, Turkey',
    phone: '+90 212 000 0000',
    lat: '41.0165',
    lng: '28.9639',
  },
  sections: {
    story: true,
    ceremony: true,
    countdown: true,
    dua: true,
    party: true,
    guidelines: true,
    gallery: true,
    location: true,
  },
}
